package com.instantgame.service;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.util.Objects;

/**
 * Writes the starter PRD template used by the generation pipeline.
 */
public final class GenerateTemplateWriter {

  /** Canonical markdown template generated by the init command. */
  public static final String TEMPLATE =
      """
      # InstantGame PRD
      
      ## Project Identity
      - Project Name: <fill-me>
      - One-line Pitch: <fill-me>
      - Core Loop: <fill-me>
      - Target Platforms: <fill-me>
      - Target Audience: <fill-me>
      - Target Session Length: <fill-me>
      - Monetization Model: <fill-me>
      
      ## Game Vision
      - Player Fantasy: <fill-me>
      - Pillar 1: <fill-me>
      - Pillar 2: <fill-me>
      - Pillar 3: <fill-me>
      - Success Criteria: <fill-me>
      
      ## Genre Checkboxes
      - [ ] Action
      - [ ] Action RPG
      - [ ] Adventure
      - [ ] Arcade
      - [ ] Auto Battler
      - [ ] Battle Royale
      - [ ] Card Game
      - [ ] City Builder
      - [ ] Deckbuilder
      - [ ] Educational
      - [ ] Endless Runner
      - [ ] Extraction
      - [ ] Farming Sim
      - [ ] Fighting
      - [ ] First-Person Shooter
      - [ ] Horror
      - [ ] Idle / Incremental
      - [ ] Immersive Sim
      - [ ] JRPG
      - [ ] Life Sim
      - [ ] Metroidvania
      - [ ] MOBA
      - [ ] MMORPG
      - [ ] Open World
      - [ ] Party
      - [ ] Puzzle
      - [ ] Racing
      - [ ] Roguelike
      - [ ] Roguelite
      - [ ] Sandbox
      - [ ] Shooter
      - [ ] Simulation
      - [ ] Soulslike
      - [ ] Sports
      - [ ] Stealth
      - [ ] Strategy
      - [ ] Survival
      - [ ] Tactical RPG
      - [ ] Third-Person Shooter
      - [ ] Tower Defense
      - [ ] Turn-Based Strategy
      - [ ] Visual Novel
      - [ ] 4X Strategy
      - [ ] RPG
      - [ ] Platformer
      - Custom Genre: <fill-me>
      
      ## Art Style Checkboxes
      - [ ] Pixel Art
      - [ ] HD-2D
      - [ ] Low Poly 3D
      - [ ] Hand Drawn 2D
      - [ ] Stylized 3D
      - [ ] Realistic / PBR
      - [ ] Cel-Shaded
      - [ ] Anime
      - [ ] Comic Book
      - [ ] Voxel
      - [ ] Isometric
      - [ ] Top-Down Retro
      - [ ] PS1 Retro
      - [ ] PS2 Retro
      - [ ] Watercolor
      - [ ] Ink / Sketch
      - [ ] Claymation
      - [ ] Diorama
      - [ ] Monochrome
      - [ ] Noir
      - [ ] Neon Sci-Fi
      - [ ] Fantasy Painterly
      - [ ] Real-Time 2D Cutout
      - [ ] Flat Vector
      - [ ] UI-First Minimal
      - [ ] Minimalist
      - Custom Art Style: <fill-me>
      
      ## Music Style Checkboxes
      - [ ] Chiptune
      - [ ] Orchestral
      - [ ] Cinematic Hybrid
      - [ ] Ambient
      - [ ] Lo-fi
      - [ ] Synthwave
      - [ ] EDM
      - [ ] House
      - [ ] Techno
      - [ ] Drum and Bass
      - [ ] Rock
      - [ ] Metal
      - [ ] Punk
      - [ ] Jazz
      - [ ] Blues
      - [ ] Hip-Hop
      - [ ] Trap
      - [ ] Folk
      - [ ] Acoustic
      - [ ] Piano Solo
      - [ ] World Fusion
      - [ ] Horror Drones
      - [ ] Industrial
      - [ ] 8-bit Retro
      - [ ] 16-bit Retro
      - Custom Music Style: <fill-me>
      
      ## Agent Toggles
      - [x] Code Agent
      - [x] Art Agent
      - [x] Music Agent
      
      ## AI Agent Commands (Optional)
      - Code Agent Command: <fill-me>
      - Art Agent Command: <fill-me>
      - Music Agent Command: <fill-me>
      - Command Contract: each command receives INSTANTGAME_PROMPT and should print markdown to stdout.
      
      ## Gameplay Mechanics
      ### Major Mechanics (Dictate Core Gameplay Directly)
      - [ ] Point and Click
      - [ ] Turn-Based Combat
      - [ ] Real-Time Combat
      - [ ] Deckbuilding Combat
      - [ ] Auto-Battling
      - [ ] Exploration / Discovery
      - [ ] Platforming
      - [ ] Puzzle Solving
      - [ ] Dialogue Choices
      - [ ] Branching Narrative
      - [ ] Resource Gathering
      - [ ] Resource Management
      - [ ] Base Building
      - [ ] Item Crafting
      - [ ] Stealth
      - [ ] Co-op Multiplayer
      - [ ] Competitive PvP
      - [ ] Rhythm / Timing
      - [ ] World Simulation / AI Ecology
      - [ ] Procedural Generation
      - [ ] Permadeath
      - [ ] Meta Progression
      - Custom Major Mechanic: <fill-me>
      
      ### Minor Mechanics (Subset / Supporting Systems)
      - [ ] Quick Time Events
      - [ ] Dialogue Reputation System
      - [ ] Companion / Party Management
      - [ ] Parkour / Movement Tech
      - [ ] Physics Puzzles
      - [ ] Logic Puzzles
      - [ ] Match-3
      - [ ] Bullet Hell Patterns
      - [ ] Dodge / Parry Timing
      - [ ] Combo Meter
      - [ ] Status Effects
      - [ ] Loadout Management
      - [ ] Skill Tree Nodes
      - [ ] Minimap / Wayfinding
      - [ ] Ping / Marker System
      - [ ] Crafting Recipes
      - [ ] Trading / Barter
      - [ ] Base Upgrades
      - Custom Minor Mechanic: <fill-me>
      
      ## Core Mechanics & Systems
      - Primary Mechanics: <fill-me>
      - Controls / Input Model: <fill-me>
      - Progression Model: <fill-me>
      - Win Condition: <fill-me>
      - Failure Condition: <fill-me>
      - Economy / Resource Loops: <fill-me>
      - Difficulty Curve Notes: <fill-me>
      
      ## Content & Scope
      - Number of Levels / Arenas: <fill-me>
      - Number of Enemy Types: <fill-me>
      - Number of Bosses / Major Encounters: <fill-me>
      - Number of Characters / Classes: <fill-me>
      - Number of Items / Abilities: <fill-me>
      - Expected Time to MVP: <fill-me>
      - Out of Scope (Explicit): <fill-me>
      
      ## Tech & Production Constraints
      - Engine / Framework: <fill-me>
      - Build Target(s): <fill-me>
      - Performance Target (FPS / Memory): <fill-me>
      - Save System Requirements: <fill-me>
      - Network / Online Requirements: <fill-me>
      - Accessibility Requirements: <fill-me>
      - Legal / Licensing Constraints: <fill-me>
      - Art Pipeline Constraints: <fill-me>
      - Audio Pipeline Constraints: <fill-me>
      
      ## Loop Settings
      - Iterations: 2
      - Test Strategy: Unit tests, content validation, MCP server checks (optional)
      
      ## Constraints
      - Scope Guardrails: <fill-me>
      
      ## Other Notes
      - Other Notes: <fill-me>
      """;

  /**
   * Writes the template only if it does not already exist.
   *
   * @param briefPath destination path
   * @return true when a new template file is created
   * @throws IOException when file operations fail
   */
  public boolean writeTemplateIfMissing(Path briefPath) throws IOException {
    Objects.requireNonNull(briefPath, "briefPath");

    if (Files.exists(briefPath)) {
      return false;
    }

    Files.writeString(
        briefPath,
        TEMPLATE,
        StandardCharsets.UTF_8,
        StandardOpenOption.CREATE_NEW,
        StandardOpenOption.WRITE);

    return true;
  }
}
